# Generated by Django 5.1.1 on 2024-09-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('stockQuantity', models.IntegerField()),
            ],
        ),
    ]
